# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit debtkit.Rmd to modify this file

## ----setup, include = FALSE---------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      fig.align = "center", out.width = "100%")


## ----decompose, fig.cap = "Annual contributions to the change in US federal debt/GDP, 2004 to 2023. Components: interest effect (red), growth effect (green, negative), primary deficit (orange, plotted positive so that a deficit adds to debt), stock-flow adjustment (grey). Dots mark the observed annual change in the debt ratio. The global financial crisis (2008 to 2010) shows a large positive interest and primary-deficit contribution. The 2020 pandemic year shows the largest single-year jump, driven by primary-deficit contribution. Source: FRED \\texttt{GFDEGDQ188S}, \\texttt{FYFSGDA188S}, \\texttt{IRLTLT01USM156N}, and \\texttt{A091RC1Q027SBEA}.", fig.alt = "A stacked column chart of annual contributions to the change in the US federal debt-to-GDP ratio from 2004 to 2023. Each year has four coloured bars: interest (red), growth (green, usually negative), primary deficit (orange), and stock-flow adjustment (grey). Black dots mark the total observed annual change in the debt ratio. Two periods stand out: 2008 to 2010 shows large positive interest and primary-deficit contributions, and 2020 shows the largest single-year jump, dominated by a very large positive orange bar."----
knitr::include_graphics("figures/fig1_decompose.pdf")


## ----cross-country, fig.cap = "Gross government debt, percentage of GDP, 1990 to 2023. Data: FRED series \\texttt{GFDEGDQ188S} (United States, aggregated to annual), \\texttt{GGGDTAGBA188N} (United Kingdom), \\texttt{DEBTTLJPA188A} (Japan). Japan reached roughly 240 per cent of GDP by 2022 and remains the outlier. The United Kingdom and the United States converged to roughly 100 per cent of GDP after the 2020 pandemic from starting points near 40 per cent in 1990.", fig.alt = "A line chart showing three time series of gross government debt as a percentage of GDP from 1990 to 2023 for Japan, the United States, and the United Kingdom. Japan rises from about 60 per cent in 1990 to roughly 240 per cent by the early 2020s and stays well above the other two countries throughout. The United States and the United Kingdom both start near 30 to 40 per cent in 1990 and rise gradually, with level jumps after 2008 and 2020, ending close to 100 to 120 per cent of GDP."----
knitr::include_graphics("figures/fig2_cross_country.pdf")


## ----fan, fig.cap = "Stochastic fan chart for US federal debt held by the public, 2023 to 2033, 2000 Monte Carlo simulations. The shaded bands show simulation quantiles: the inner band is the 50 per cent interval (25th to 75th percentile), the outer band the 80 per cent interval (10th to 90th). The solid blue line is the simulation median; the red dashed line is the deterministic baseline that holds macro conditions fixed at their 2023 values. Shocks are drawn from a first-order VAR fitted to 2004 to 2023 residuals on growth, interest rate, and primary balance.", fig.alt = "A fan chart projecting US federal debt held by the public from 2023 to 2033. A dark blue solid line traces the simulation median, rising gently over time. A red dashed line marks the deterministic baseline. Two concentric shaded blue bands show the 50 per cent and 80 per cent uncertainty intervals, widening steadily from 2023 onward to span a broad range by 2033."----
knitr::include_graphics("figures/fig3_fan.pdf")


## ----stress, fig.cap = "US federal debt/GDP under IMF standardised stress tests, five-year horizon from 2023. Baseline (grey) plus six alternatives: a one percentage-point growth shock, a two percentage-point interest shock, a one percentage-point primary-balance shock, a combined macro shock, an exchange-rate shock (US dollar debt, so effectively no impact), and a contingent-liability realisation. The interest shock is the most adverse single scenario for an advanced economy with rising near-term refinancing needs.", fig.alt = "A line chart showing seven five-year debt-to-GDP projections starting from 2023. A thick grey baseline rises modestly over five years. Six coloured scenario lines diverge from the baseline: the interest-rate shock climbs the fastest and sits well above the baseline by year five, the combined macro and contingent-liability shocks also rise well above baseline, the growth and primary-balance shocks sit moderately above, and the exchange-rate line tracks the baseline closely because US debt is dollar denominated."----
knitr::include_graphics("figures/fig4_stress.pdf")


## ----bohn, fig.cap = "Bohn (1998) fiscal reaction function, US 2004 to 2023. Points are annual observations, coloured by year (blue 2004, red 2023). Red line: OLS fit with Newey-West standard errors. Dashed line at zero primary balance. The positive slope is consistent with a sustainable fiscal reaction function, but the 2004 to 2023 sample includes two large unprecedented shocks (the 2008 crisis and the 2020 pandemic) that widen the confidence interval around the slope estimate.", fig.alt = "A scatter plot with lagged debt-to-GDP on the horizontal axis and the primary balance on the vertical axis, for US annual observations from 2004 to 2023. Points are coloured on a blue-to-red gradient by year. A red regression line slopes gently upward across the cloud, consistent with a positive but modest reaction coefficient. A horizontal dashed line marks zero primary balance, with most points sitting below it and two very low outliers corresponding to 2009 and 2020."----
knitr::include_graphics("figures/fig5_bohn.pdf")


## ----debt-panel---------------------------------------------------------------
debt_panel <- data.frame(
  Country = c("United States", "United Kingdom"),
  `Debt/GDP (first)` = c("40.9% (1990)", "30.2% (1990)"),
  `Debt/GDP (latest)` = c("118.0% (2024)", "131.1% (2024)"),
  `Peak (year)` = c("126.4% (2020)", "194.7% (2020)"),
  Change = c("+77.0 pp", "+100.9 pp"),
  check.names = FALSE,
  stringsAsFactors = FALSE
)
knitr::kable(
  debt_panel,
  caption = "Central government debt, two advanced economies: first and latest observations plus peak. Data: World Bank \\texttt{GC.DOD.TOTL.GD.ZS}. The United Kingdom and the United States rose from roughly 30 to 40 per cent in 1990 to above 100 per cent by 2024.",
  booktabs = TRUE
)

